name: culdesac_chat
description: "A simple chat application built with Flutter."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0 # The intl package is used for internationalization and localization.
  flutter_markdown: ^0.6.18 # The flutter_markdown package is used to render Markdown text in Flutter.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  provider: ^6.1.2
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: ArchivoBlack
      fonts:
        - asset: fonts/ArchivoBlack-Regular.ttf
          weight: 400
    
    - family: BebasKai
      fonts:
        - asset: fonts/BebasKai.ttf
          weight: 400
    
    - family: EBGaramond
      fonts:
        - asset: fonts/EBGaramond-Regular.ttf
          weight: 400
        - asset: fonts/EBGaramond-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/EBGaramond-Medium.ttf
          weight: 500
        - asset: fonts/EBGaramond-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/EBGaramond-SemiBold.ttf
          weight: 600
        - asset: fonts/EBGaramond-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/EBGaramond-Bold.ttf
          weight: 700
        - asset: fonts/EBGaramond-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/EBGaramond-ExtraBold.ttf
          weight: 800
        - asset: fonts/EBGaramond-ExtraBoldItalic.ttf
          weight: 800
          style: italic
    
    - family: Helvetica
      fonts:
        - asset: fonts/Helvetica.ttf
          weight: 400
        - asset: fonts/Helvetica-Oblique.ttf
          weight: 400
          style: italic
        - asset: fonts/helvetica-light-587ebe5a59211.ttf
          weight: 300
        - asset: fonts/Helvetica-Bold.ttf
          weight: 700
        - asset: fonts/Helvetica-BoldOblique.ttf
          weight: 700
          style: italic
    
    - family: LexendMega
      fonts:
        - asset: fonts/LexendMega-Thin.ttf
          weight: 100
        - asset: fonts/LexendMega-ExtraLight.ttf
          weight: 200
        - asset: fonts/LexendMega-Light.ttf
          weight: 300
        - asset: fonts/LexendMega-Regular.ttf
          weight: 400
        - asset: fonts/LexendMega-Medium.ttf
          weight: 500
        - asset: fonts/LexendMega-SemiBold.ttf
          weight: 600
        - asset: fonts/LexendMega-Bold.ttf
          weight: 700
        - asset: fonts/LexendMega-ExtraBold.ttf
          weight: 800
        - asset: fonts/LexendMega-Black.ttf
          weight: 900
    
    - family: MabryPro
      fonts:
        - asset: fonts/MabryPro-Light.ttf
          weight: 300
        - asset: fonts/MabryPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/MabryPro-Regular.ttf
          weight: 400
        - asset: fonts/MabryPro-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/MabryPro-Medium.ttf
          weight: 500
        - asset: fonts/MabryPro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/MabryPro-Bold.ttf
          weight: 700
        - asset: fonts/MabryPro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/MabryPro-Black.ttf
          weight: 900
        - asset: fonts/MabryPro-BlackItalic.ttf
          weight: 900
          style: italic
    
    - family: PublicSans
      fonts:
        - asset: fonts/PublicSans-Thin.ttf
          weight: 100
        - asset: fonts/PublicSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/PublicSans-ExtraLight.ttf
          weight: 200
        - asset: fonts/PublicSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/PublicSans-Light.ttf
          weight: 300
        - asset: fonts/PublicSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/PublicSans-Regular.ttf
          weight: 400
        - asset: fonts/PublicSans-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/PublicSans-Medium.ttf
          weight: 500
        - asset: fonts/PublicSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/PublicSans-SemiBold.ttf
          weight: 600
        - asset: fonts/PublicSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/PublicSans-Bold.ttf
          weight: 700
        - asset: fonts/PublicSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/PublicSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/PublicSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/PublicSans-Black.ttf
          weight: 900
        - asset: fonts/PublicSans-BlackItalic.ttf
          weight: 900
          style: italic
