// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqg7Nu4KraUvRRwxn9G1v5YnN9-dLHwTk',
    appId: '1:38021234140:web:8b37adaeb4517876d7a319',
    messagingSenderId: '38021234140',
    projectId: 'culdesac-chat',
    authDomain: 'culdesac-chat.firebaseapp.com',
    storageBucket: 'culdesac-chat.firebasestorage.app',
    measurementId: 'G-BK7NPNE29F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0kjdnz27Q9a-IwXbGinWmoespH5Q1iXY',
    appId: '1:38021234140:android:39a03747495f07ffd7a319',
    messagingSenderId: '38021234140',
    projectId: 'culdesac-chat',
    storageBucket: 'culdesac-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUdHP2kRFNBRxINav0aHEWDJdHnIPuZE8',
    appId: '1:38021234140:ios:99161446ca565d04d7a319',
    messagingSenderId: '38021234140',
    projectId: 'culdesac-chat',
    storageBucket: 'culdesac-chat.firebasestorage.app',
    iosBundleId: 'com.example.culdesacChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUdHP2kRFNBRxINav0aHEWDJdHnIPuZE8',
    appId: '1:38021234140:ios:99161446ca565d04d7a319',
    messagingSenderId: '38021234140',
    projectId: 'culdesac-chat',
    storageBucket: 'culdesac-chat.firebasestorage.app',
    iosBundleId: 'com.example.culdesacChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqg7Nu4KraUvRRwxn9G1v5YnN9-dLHwTk',
    appId: '1:38021234140:web:7ee49eec0d46a569d7a319',
    messagingSenderId: '38021234140',
    projectId: 'culdesac-chat',
    authDomain: 'culdesac-chat.firebaseapp.com',
    storageBucket: 'culdesac-chat.firebasestorage.app',
    measurementId: 'G-2X6F7G01G6',
  );

}